# -*- coding: utf-8 -*-
"""kiragami3dcreator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dMkW8Jw0cIXApfGFypA6sXKaw88qxBuG
"""

import math
import numpy as np
import trimesh

# -------------------------------------------------------------
# 1. PARAMETERS & INPUT DATA
# -------------------------------------------------------------
vertical_drop = 10.62     # Max Z-drop (inches)
N_cuts = 8                # 8 cuts / bridges per ring
kerf_factor = 0.85        # Ratio of ribbon width to ring spacing
sheet_thickness = 0.015   # CFD solid thickness
MAKE_WATERTIGHT_SOLID = True

ring_data = [
    (1,  0.750000, 36.5, 8.5), (2,  0.833234, 36.9, 8.1), (3,  0.934708, 37.3, 7.7),
    (4,  1.044437, 37.7, 7.3), (5,  1.159894, 38.1, 6.9), (6,  1.279807, 38.5, 6.5),
    (7,  1.403396, 38.5, 6.5), (8,  1.530127, 38.5, 6.5), (9,  1.659611, 38.5, 6.5),
    (10, 1.791553, 38.5, 6.5), (11, 1.925716, 38.5, 6.5), (12, 2.061910, 38.5, 6.5),
    (13, 2.199976, 38.5, 6.5), (14, 2.339780, 38.5, 6.5), (15, 2.481209, 38.5, 6.5),
    (16, 2.624162, 38.5, 6.5), (17, 2.768554, 38.5, 6.5), (18, 2.914305, 38.5, 6.5),
    (19, 3.061350, 38.5, 6.5), (20, 3.209625, 38.5, 6.5), (21, 3.359076, 38.5, 6.5),
    (22, 3.509653, 38.5, 6.5), (23, 3.661309, 38.5, 6.5), (24, 3.814004, 38.5, 6.5),
    (25, 3.967698, 38.5, 6.5), (26, 4.122355, 38.5, 6.5), (27, 4.277944, 38.5, 6.5),
    (28, 4.434433, 38.5, 6.5), (29, 4.591794, 38.5, 6.5), (30, 4.750000, 38.5, 6.5)
]

r_dep = [r[1] for r in ring_data]
gap_deg = [r[3] for r in ring_data]
r_max = r_dep[-1]

def get_z(r): return -vertical_drop * (r / r_max)**2
def get_w(k): return (r_dep[k+1] - r_dep[k]) * kerf_factor if k < len(r_dep)-1 else (r_dep[-1] - r_dep[-2]) * kerf_factor

global_verts = []
global_faces = []

def add_strip(r1, z1, w1, th1, r2, z2, w2, th2, segs):
    """Draws a continuous quad strip connecting two coordinates."""
    idx_start = len(global_verts)
    for j in range(segs + 1):
        t = j / segs
        r, z, w = r1 + t*(r2-r1), z1 + t*(z2-z1), w1 + t*(w2-w1)
        th = math.radians(th1 + t*(th2-th1))
        global_verts.extend([[(r - w/2)*math.cos(th), (r - w/2)*math.sin(th), z],
                             [(r + w/2)*math.cos(th), (r + w/2)*math.sin(th), z]])
        if j > 0:
            v = idx_start + j * 2
            global_faces.extend([[v-2, v-1, v], [v-1, v+1, v]])

# -------------------------------------------------------------
# 2. GENERATE EXPANDED KINEMATICS (OPEN HEXAGONS)
# -------------------------------------------------------------
for k in range(len(r_dep)):
    r_k, z_k, w_k, gap_k = r_dep[k], get_z(r_dep[k]), get_w(k), gap_deg[k]

    # NEW: Calculate true bridge width (union of upper and lower ribbons)
    w_prev = get_w(k-1) if k > 0 else w_k
    w_bridge = w_k + w_prev

    stagger_k = 0 if k % 2 == 0 else 22.5

    for i in range(N_cuts):
        th_c = i * 45 + stagger_k
        th_L, th_R = th_c - gap_k/2, th_c + gap_k/2

        # 1. Horizontal Bridge (Hinge) -> Now uses double-wide w_bridge
        add_strip(r_k, z_k, w_bridge, th_L, r_k, z_k, w_bridge, th_R, segs=2)

        # 2. Continuous Rim bridging gaps for Top (0) and Bottom (29)
        if k == 0 or k == len(r_dep) - 1:
            next_th_L = ((i+1) * 45 + stagger_k) - gap_k/2
            add_strip(r_k, z_k, w_bridge, th_R, r_k, z_k, w_bridge, next_th_L, segs=3)

        # 3. Diagonal Ribbons twisting down to ring k+1 (remain standard w_k width)
        if k < len(r_dep) - 1:
            r_k1, z_k1, w_k1, gap_k1 = r_dep[k+1], get_z(r_dep[k+1]), get_w(k+1), gap_deg[k+1]

            # Left twisted ribbon
            botL_R = (th_c - 22.5) + gap_k1/2
            add_strip(r_k1, z_k1, w_k1, botL_R, r_k, z_k, w_k, th_L, segs=3)

            # Right twisted ribbon
            botR_L = (th_c + 22.5) - gap_k1/2
            add_strip(r_k, z_k, w_k, th_R, r_k1, z_k1, w_k1, botR_L, segs=3)

# -------------------------------------------------------------
# 3. ADD CENTER HOLE CAP
# -------------------------------------------------------------
cap_idx = len(global_verts)
global_verts.append([0, 0, 0])  # Apex origin at Z=0

# NEW: Offset the cap radius to account for the wider apex rim
w_bridge_top = get_w(0) * 2
cap_r, cap_z = r_dep[0] - w_bridge_top/2, get_z(r_dep[0])

cap_angles = []
for i in range(N_cuts):
    th_c, next_th_c = i * 45, (i+1) * 45
    cap_angles.extend(np.linspace(th_c - gap_deg[0]/2, th_c + gap_deg[0]/2, 3)[:-1])
    cap_angles.extend(np.linspace(th_c + gap_deg[0]/2, next_th_c - gap_deg[0]/2, 4)[:-1])

for idx, th_deg in enumerate(cap_angles):
    th = math.radians(th_deg)
    global_verts.append([cap_r * math.cos(th), cap_r * math.sin(th), cap_z])

N_cap = len(cap_angles)
for idx in range(N_cap):
    next_idx = (idx + 1) % N_cap
    global_faces.append([cap_idx, cap_idx + next_idx + 1, cap_idx + idx + 1])

# -------------------------------------------------------------
# 4. EXTRUDE TO WATERTIGHT SOLID
# -------------------------------------------------------------
if MAKE_WATERTIGHT_SOLID:
    print("Extruding shell to watertight 3D solid...")
    normals = shell.vertex_normals
    v_top = shell.vertices + normals * (sheet_thickness / 2.0)
    v_bot = shell.vertices - normals * (sheet_thickness / 2.0)
    V_solid = np.vstack((v_top, v_bot))
    N_v = len(v_top)

    F_solid = np.vstack((shell.faces, np.fliplr(shell.faces) + N_v))

    # Stitch open boundaries to seal the volume
    edges = shell.edges_sorted
    unique_edges, counts = np.unique(edges, axis=0, return_counts=True)
    boundary_edges = unique_edges[counts == 1]

    stitch_faces = []
    for e in boundary_edges:
        v0, v1 = e[0], e[1]
        stitch_faces.extend([[v0, v1, v1 + N_v], [v0, v1 + N_v, v0 + N_v]])

    shell = trimesh.Trimesh(vertices=V_solid, faces=np.vstack((F_solid, stitch_faces)))
    trimesh.repair.fix_normals(shell)
    print(f"Solid topology check: {shell.is_watertight} (Expected True)")

out_file = "kirigami_hex_solid.stl"
shell.export(out_file)
print(f"Exported {out_file} successfully.")
files.download(out_file)